apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
data:
  hazelcast.yaml: |-
    hazelcast:
      cluster-name: dev
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-name: hazelcast-headless