apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 5000
        hostPort: 5000
        listenAddress: "0.0.0.0"
        protocol: tcp
  - role: worker