name: Integrational tests
on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:
  run-tests:
    name: Run Intergrational tests using Kind
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"

      - name: Deploy to Kuberenetes
        run: |-
          kubectl apply -f rbac.yaml
          kubectl apply -f config.yaml
          kubectl apply -f deployment.yaml

      - name: Test for successful Deployment
        run: |-
          kubectl wait --for=condition=ready pod/hazelcast-sidecar-0 --timeout=150s
          kubectl wait --for=condition=ready pod/hazelcast-sidecar-1 --timeout=120s

      - name: Test application
        run: |-

          kubectl create job curl-put --image=curlimages/curl -- curl "hazelcast-sidecar:5000/put?key=someKey&value=someValue"
          kubectl wait --for=condition=complete job/curl-put --timeout=200s

          kubectl create job curl-get --image=curlimages/curl -- curl "hazelcast-sidecar:5000/put?key=someKey&value=someValue"
          kubectl wait --for=condition=complete job/curl-get --timeout=200s

          kubectl logs job/curl-get

      - name: Log status on failure
        if: ${{ failure() }}
        run: |-
          kubectl describe pod/hazelcast-sidecar-0
          kubectl describe pod/hazelcast-sidecar-1
          exit 1
