name: Integrational tests
on:
  push:
    paths-ignore:
      - 'doc/**'

jobs:
  run-tests:
    name: Run Intergrational tests using Kind
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"
          config: kind.yaml

      - name: Deploy to Kuberenetes
        run: |-
          kubectl apply -f rbac.yaml
          kubectl apply -f config.yaml
          kubectl apply -f deployment.yaml

      - name: Test for successful Deployment
        run: |-
          kubectl wait --for=condition=ready pod/hazelcast-sidecar-0 --timeout=150s
          kubectl wait --for=condition=ready pod/hazelcast-sidecar-1 --timeout=120s

      - name: Query application
        run: |-
          clusterIP=$(kubectl get svc hazelcast-sidecar -o jsonpath='{$.spec.clusterIP}')
          kubectl run curl --image=curlimages/curl -- "$clusterIP:5000/put?key=someKey&value=someValue"
          kubectl wait --for=condition=ready pod/curl --timeout=150s

      - name: Log status on failure
        if: ${{ failure() }}
        run: |-
          kubectl describe pod/hazelcast-sidecar-0
          kubectl describe pod/hazelcast-sidecar-1
          exit 1
